### ISSUE TITLE
XGM ROM Builder doesn't function properly on Linux

### ISSUE THREAD

**Issue by freq-mod** [Stephane-D/SGDK#343]
With Java 8 installed, the ROM builder itself works fine. xgmtool was build properly via Cmake 3.30 and GCC 14, trying to add VGM file to ROM builder results in:
```
exec(xgmtool "/home/anon/Pobrane/10 Kurumi's Theme.vgm" out.xgc -s) error : Cannot run program "xgmtool" (in directory "."): error=2, No such file or directory
java.lang.NullPointerException
        at main.MainFrame.compileVGM(MainFrame.java:372)
        at main.MainFrame.compileVGM(MainFrame.java:403)
        at main.MainFrame.addVGM(MainFrame.java:327)
        at main.MainFrame$VGMAdder.run(MainFrame.java:430)
        at java.lang.Thread.run(Thread.java:750)```

unix xgmtool executable is placed in the same directory as the ROM builder, and on itself functions properly. I don't know why builder refuses to "see" it, like on Windows.

**Comment by Stephane-D** [comment]
I guess it probably need to be called ./xgmtool on linux system ?
